-- ============================================================================
-- ELEVATE Fashion Store — ВТОРАЯ партия наполнения каталога.
-- 48 новых товаров, 45 новых пользователей, ~150 уникальных отзывов.
--
-- Все id НОВЫЕ и НЕ конфликтуют с первой партией:
--   товары  elevate-w-2xx / elevate-m-2xx
--   юзеры   user-041..085
--   отзывы  rev-201..356
-- Часть отзывов оставлена от уже существующих покупателей (user-001..040) —
-- возвращающиеся клиенты, так правдоподобнее.
--
-- Применение: Supabase → SQL Editor → New query → Run. Идемпотентно.
-- ============================================================================

BEGIN;

-- Категории (на случай чистой БД; существующие не трогаются)
INSERT INTO categories (id, name, slug, description, is_active, sort_order, locale)
VALUES
  ('women',       'Женское',   'zhenskoe',   'Женская коллекция ELEVATE', true, 1, 'ru'),
  ('men',         'Мужское',   'muzhskoe',   'Мужская коллекция ELEVATE', true, 2, 'ru'),
  ('new',         'Новинки',   'novinki',    'Новые поступления',         true, 3, 'ru'),
  ('collections', 'Коллекции', 'kollektsii', 'Избранные подборки',        true, 4, 'ru')
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- 1. ТОВАРЫ (48 новых)
-- ============================================================================
INSERT INTO products (
  id, name, slug, sku, description, short_description, price, compare_at_price,
  stock, category_id, brand, country, composition, color,
  in_stock, featured, is_featured, is_new, is_active, is_sale, tags, images,
  created_at, updated_at
) VALUES
-- ── ЖЕНСКОЕ elevate-w-201..226 ──
('elevate-w-201','Платье-рубашка «Linen Shirt»','dress-linen-shirt','ELV-W-201',
 'Платье-рубашка из чистого льна с поясом и накладными карманами. Свободный крой, дышит в жару.',
 'Платье-рубашка из льна',5490,NULL,28,'women','ELEVATE','Турция','100% лён','Оливковый',
 true,false,false,true,true,false,ARRAY['лето','новинка'],ARRAY['https://picsum.photos/seed/elevate-w-201/800/1000','https://picsum.photos/seed/elevate-w-201b/800/1000'],
 NOW() - INTERVAL '24 days', NOW()),
('elevate-w-202','Платье вечернее «Velvet Night»','dress-velvet-night','ELV-W-202',
 'Бархатное платье в пол с открытой спиной. Глубокий цвет и мягкая фактура для особых случаев.',
 'Бархатное вечернее платье',9990,12990,14,'women','ELEVATE','Китай','92% полиэстер, 8% эластан','Бордовый',
 true,true,true,false,true,true,ARRAY['вечернее','хит'],ARRAY['https://picsum.photos/seed/elevate-w-202/800/1000','https://picsum.photos/seed/elevate-w-202b/800/1000'],
 NOW() - INTERVAL '38 days', NOW()),
('elevate-w-203','Топ «Bardot»','top-bardot','ELV-W-203',
 'Топ с открытыми плечами и резинкой по краю. Эластичный трикотаж, подчёркивает линию плеч.',
 'Топ с открытыми плечами',1990,NULL,40,'women','ELEVATE','Узбекистан','95% вискоза, 5% эластан','Чёрный',
 true,false,false,false,true,false,ARRAY['базовое'],ARRAY['https://picsum.photos/seed/elevate-w-203/800/1000','https://picsum.photos/seed/elevate-w-203b/800/1000'],
 NOW() - INTERVAL '19 days', NOW()),
('elevate-w-204','Юбка «Satin Slip»','skirt-satin-slip','ELV-W-204',
 'Атласная юбка миди по косой с разрезом. Струится и красиво играет на свету.',
 'Атласная юбка миди по косой',4290,NULL,24,'women','ELEVATE','Китай','100% полиэстер (атлас)','Шампань',
 true,false,false,false,true,false,ARRAY['вечернее'],ARRAY['https://picsum.photos/seed/elevate-w-204/800/1000','https://picsum.photos/seed/elevate-w-204b/800/1000'],
 NOW() - INTERVAL '31 days', NOW()),
('elevate-w-205','Джинсы клёш «Flare 70s»','jeans-flare-70s','ELV-W-205',
 'Джинсы клёш с высокой посадкой в стиле 70-х. Удлиняют ноги, плотный деним держит силуэт.',
 'Джинсы клёш с высокой посадкой',5290,NULL,30,'women','ELEVATE','Китай','98% хлопок, 2% эластан','Синий',
 true,false,false,false,true,false,ARRAY['деним'],ARRAY['https://picsum.photos/seed/elevate-w-205/800/1000','https://picsum.photos/seed/elevate-w-205b/800/1000'],
 NOW() - INTERVAL '27 days', NOW()),
('elevate-w-206','Кейп-пальто «Cape Elegance»','coat-cape-elegance','ELV-W-206',
 'Пальто-кейп свободного силуэта с прорезями для рук. Эффектная вещь на прохладную погоду.',
 'Пальто-кейп свободного кроя',12990,NULL,12,'women','ELEVATE','Китай','68% шерсть, 32% полиэстер','Серый',
 true,false,true,false,true,false,ARRAY['демисезон'],ARRAY['https://picsum.photos/seed/elevate-w-206/800/1000','https://picsum.photos/seed/elevate-w-206b/800/1000'],
 NOW() - INTERVAL '40 days', NOW()),
('elevate-w-207','Куртка «Biker Lux»','jacket-biker-lux','ELV-W-207',
 'Косуха из мягкой эко-кожи с молниями и поясом. Дерзкий силуэт, аккуратная фурнитура.',
 'Косуха из эко-кожи',7990,NULL,20,'women','ELEVATE','Китай','Эко-кожа (100% полиуретан)','Чёрный',
 true,true,true,true,true,false,ARRAY['демисезон','хит'],ARRAY['https://picsum.photos/seed/elevate-w-207/800/1000','https://picsum.photos/seed/elevate-w-207b/800/1000'],
 NOW() - INTERVAL '22 days', NOW()),
('elevate-w-208','Водолазка «Merino Roll»','turtleneck-merino','ELV-W-208',
 'Тонкая водолазка из мериносовой шерсти. Не колется, отлично тянется и держит тепло.',
 'Водолазка из мериноса',3990,NULL,34,'women','ELEVATE','Китай','100% шерсть мериноса','Молочный',
 true,false,false,false,true,false,ARRAY['зима','базовое'],ARRAY['https://picsum.photos/seed/elevate-w-208/800/1000','https://picsum.photos/seed/elevate-w-208b/800/1000'],
 NOW() - INTERVAL '17 days', NOW()),
('elevate-w-209','Жилет «Tailored Vest»','vest-tailored','ELV-W-209',
 'Костюмный удлинённый жилет на подкладке. Носится как самостоятельная вещь или поверх рубашки.',
 'Удлинённый костюмный жилет',4490,NULL,22,'women','ELEVATE','Турция','64% полиэстер, 32% вискоза, 4% эластан','Бежевый',
 true,false,false,true,true,false,ARRAY['офис','новинка'],ARRAY['https://picsum.photos/seed/elevate-w-209/800/1000','https://picsum.photos/seed/elevate-w-209b/800/1000'],
 NOW() - INTERVAL '15 days', NOW()),
('elevate-w-210','Платье-футляр «Sheath Classic»','dress-sheath-classic','ELV-W-210',
 'Классическое платье-футляр до колена из плотной костюмной ткани. Строгий силуэт для офиса.',
 'Платье-футляр для офиса',5990,NULL,18,'women','ELEVATE','Китай','70% полиэстер, 26% вискоза, 4% эластан','Тёмно-синий',
 true,false,false,false,true,false,ARRAY['офис'],ARRAY['https://picsum.photos/seed/elevate-w-210/800/1000','https://picsum.photos/seed/elevate-w-210b/800/1000'],
 NOW() - INTERVAL '34 days', NOW()),
('elevate-w-211','Свитер «Chunky Turtleneck»','sweater-chunky-turtleneck','ELV-W-211',
 'Свитер крупной вязки с высоким горлом. Объёмный и тёплый, с добавлением шерсти.',
 'Свитер крупной вязки с горлом',5290,NULL,26,'women','ELEVATE','Китай','45% шерсть, 35% акрил, 20% полиамид','Горчичный',
 true,false,false,false,true,false,ARRAY['зима','уют'],ARRAY['https://picsum.photos/seed/elevate-w-211/800/1000','https://picsum.photos/seed/elevate-w-211b/800/1000'],
 NOW() - INTERVAL '20 days', NOW()),
('elevate-w-212','Майка «Silk Cami»','cami-silk','ELV-W-212',
 'Шёлковая майка на тонких бретелях с косым кроем. Лёгкая база под жакет или отдельно.',
 'Шёлковая майка на бретелях',2990,NULL,32,'women','ELEVATE','Италия','100% шёлк','Пудровый',
 true,false,false,false,true,false,ARRAY['базовое'],ARRAY['https://picsum.photos/seed/elevate-w-212/800/1000','https://picsum.photos/seed/elevate-w-212b/800/1000'],
 NOW() - INTERVAL '13 days', NOW()),
('elevate-w-213','Брюки палаццо «Wide Palazzo»','pants-wide-palazzo','ELV-W-213',
 'Широкие брюки палаццо с высокой талией. Струящаяся ткань, удлиняют силуэт.',
 'Широкие брюки палаццо',4690,NULL,24,'women','ELEVATE','Турция','100% вискоза','Чёрный',
 true,false,false,false,true,false,ARRAY['офис','лето'],ARRAY['https://picsum.photos/seed/elevate-w-213/800/1000','https://picsum.photos/seed/elevate-w-213b/800/1000'],
 NOW() - INTERVAL '29 days', NOW()),
('elevate-w-214','Комбинезон «Utility Jumpsuit»','jumpsuit-utility','ELV-W-214',
 'Комбинезон в утилитарном стиле с поясом и карманами. Практичный и собранный образ в одной вещи.',
 'Комбинезон в утилитарном стиле',6490,NULL,16,'women','ELEVATE','Китай','98% хлопок, 2% эластан','Хаки',
 true,false,false,true,true,false,ARRAY['новинка'],ARRAY['https://picsum.photos/seed/elevate-w-214/800/1000','https://picsum.photos/seed/elevate-w-214b/800/1000'],
 NOW() - INTERVAL '11 days', NOW()),
('elevate-w-215','Кардиган «Long Line Knit»','cardigan-long-line','ELV-W-215',
 'Удлинённый кардиган без застёжки из мягкой пряжи. Уютный, хорошо садится по фигуре сверху.',
 'Удлинённый кардиган',4990,NULL,22,'women','ELEVATE','Китай','50% вискоза, 28% полиамид, 22% шерсть','Серо-бежевый',
 true,false,false,false,true,false,ARRAY['уют','демисезон'],ARRAY['https://picsum.photos/seed/elevate-w-215/800/1000','https://picsum.photos/seed/elevate-w-215b/800/1000'],
 NOW() - INTERVAL '26 days', NOW()),
('elevate-w-216','Блейзер «Boyfriend Blazer»','blazer-boyfriend','ELV-W-216',
 'Свободный блейзер в мужском стиле на подкладке. Универсальная вещь к джинсам и брюкам.',
 'Свободный блейзер оверсайз',7490,NULL,20,'women','ELEVATE','Турция','63% полиэстер, 33% вискоза, 4% эластан','Серый',
 true,false,true,false,true,false,ARRAY['офис'],ARRAY['https://picsum.photos/seed/elevate-w-216/800/1000','https://picsum.photos/seed/elevate-w-216b/800/1000'],
 NOW() - INTERVAL '36 days', NOW()),
('elevate-w-217','Юбка джинсовая «Denim A-line»','skirt-denim-aline','ELV-W-217',
 'Джинсовая юбка А-силуэта с пуговицами спереди. Плотный деним, длина мини.',
 'Джинсовая юбка А-силуэта',3490,NULL,26,'women','ELEVATE','Китай','100% хлопок','Голубой',
 true,false,false,false,true,false,ARRAY['деним','лето'],ARRAY['https://picsum.photos/seed/elevate-w-217/800/1000','https://picsum.photos/seed/elevate-w-217b/800/1000'],
 NOW() - INTERVAL '42 days', NOW()),
('elevate-w-218','Платье «Polka Tea Dress»','dress-polka-tea','ELV-W-218',
 'Лёгкое чайное платье в горошек с рукавом и юбкой-солнце. Романтичный ретро-силуэт.',
 'Чайное платье в горошек',5790,NULL,22,'women','ELEVATE','Бангладеш','100% вискоза','Тёмно-синий в горошек',
 true,false,false,true,true,false,ARRAY['лето','новинка'],ARRAY['https://picsum.photos/seed/elevate-w-218/800/1000','https://picsum.photos/seed/elevate-w-218b/800/1000'],
 NOW() - INTERVAL '18 days', NOW()),
('elevate-w-219','Пальто стёганое «Quilted Coat»','coat-quilted','ELV-W-219',
 'Длинное стёганое пальто с утеплителем и поясом. Тёплое и лёгкое, держит форму.',
 'Длинное стёганое пальто',11490,13990,14,'women','ELEVATE','Китай','100% полиэстер; наполнитель 100% полиэстер','Чёрный',
 true,true,true,true,true,true,ARRAY['зима','хит'],ARRAY['https://picsum.photos/seed/elevate-w-219/800/1000','https://picsum.photos/seed/elevate-w-219b/800/1000'],
 NOW() - INTERVAL '30 days', NOW()),
('elevate-w-220','Худи «Crop Hoodie»','hoodie-crop','ELV-W-220',
 'Укороченное худи с начёсом и кулиской. Спортивно-повседневный образ, мягкий внутри.',
 'Укороченное худи с начёсом',3290,NULL,30,'women','ELEVATE','Узбекистан','80% хлопок, 20% полиэстер','Лавандовый',
 true,false,false,false,true,false,ARRAY['спорт','базовое'],ARRAY['https://picsum.photos/seed/elevate-w-220/800/1000','https://picsum.photos/seed/elevate-w-220b/800/1000'],
 NOW() - INTERVAL '23 days', NOW()),
('elevate-w-221','Джоггеры «Soft Jogger»','pants-soft-jogger','ELV-W-221',
 'Мягкие джоггеры с манжетами и карманами. Комфорт для дома и прогулок, не теряют форму.',
 'Мягкие трикотажные джоггеры',2990,NULL,34,'women','ELEVATE','Вьетнам','77% хлопок, 18% полиэстер, 5% эластан','Серый меланж',
 true,false,false,false,true,false,ARRAY['спорт','уют'],ARRAY['https://picsum.photos/seed/elevate-w-221/800/1000','https://picsum.photos/seed/elevate-w-221b/800/1000'],
 NOW() - INTERVAL '21 days', NOW()),
('elevate-w-222','Рубашка «Flannel Check»','shirt-flannel-check','ELV-W-222',
 'Фланелевая рубашка в клетку свободного кроя. Мягкая и тёплая, носится навыпуск.',
 'Фланелевая рубашка в клетку',3690,NULL,26,'women','ELEVATE','Китай','100% хлопок (фланель)','Красная клетка',
 true,false,false,false,true,false,ARRAY['демисезон'],ARRAY['https://picsum.photos/seed/elevate-w-222/800/1000','https://picsum.photos/seed/elevate-w-222b/800/1000'],
 NOW() - INTERVAL '33 days', NOW()),
('elevate-w-223','Бомбер «Satin Bomber»','jacket-satin-bomber','ELV-W-223',
 'Атласный бомбер с рёбрами на манжетах и вышивкой на спине. Лёгкий блеск, нарядный casual.',
 'Атласный бомбер с вышивкой',5990,NULL,18,'women','ELEVATE','Китай','100% полиэстер','Изумрудный',
 true,false,false,true,true,false,ARRAY['демисезон','новинка'],ARRAY['https://picsum.photos/seed/elevate-w-223/800/1000','https://picsum.photos/seed/elevate-w-223b/800/1000'],
 NOW() - INTERVAL '16 days', NOW()),
('elevate-w-224','Юбка плиссе «Pleated Maxi»','skirt-pleated-maxi','ELV-W-224',
 'Длинная плиссированная юбка в пол. Лёгкая, развевается при ходьбе, держит складку.',
 'Длинная плиссированная юбка',4790,NULL,22,'women','ELEVATE','Турция','100% полиэстер','Пыльно-розовый',
 true,false,false,false,true,false,ARRAY['лето','вечернее'],ARRAY['https://picsum.photos/seed/elevate-w-224/800/1000','https://picsum.photos/seed/elevate-w-224b/800/1000'],
 NOW() - INTERVAL '28 days', NOW()),
('elevate-w-225','Жакет «Linen Blazer»','blazer-linen','ELV-W-225',
 'Лёгкий льняной блейзер на лето без подкладки. Дышит, смотрится аккуратно даже в жару.',
 'Льняной блейзер без подкладки',6290,NULL,18,'women','ELEVATE','Турция','55% лён, 45% вискоза','Бежевый',
 true,false,false,false,true,false,ARRAY['лето','офис'],ARRAY['https://picsum.photos/seed/elevate-w-225/800/1000','https://picsum.photos/seed/elevate-w-225b/800/1000'],
 NOW() - INTERVAL '44 days', NOW()),
('elevate-w-226','Платье «Ribbed Bodycon»','dress-ribbed-bodycon','ELV-W-226',
 'Облегающее платье в рубчик длины миди. Эластичный трикотаж подчёркивает фигуру.',
 'Облегающее платье в рубчик',3990,NULL,24,'women','ELEVATE','Китай','92% вискоза, 8% эластан','Чёрный',
 true,false,false,false,true,false,ARRAY['базовое','вечернее'],ARRAY['https://picsum.photos/seed/elevate-w-226/800/1000','https://picsum.photos/seed/elevate-w-226b/800/1000'],
 NOW() - INTERVAL '14 days', NOW()),
-- ── МУЖСКОЕ elevate-m-201..222 ──
('elevate-m-201','Рубашка «Linen Resort»','shirt-linen-resort','ELV-M-201',
 'Льняная рубашка свободного кроя с открытым воротником. Лёгкая, идеальна для отдыха и жары.',
 'Льняная рубашка для отдыха',3990,NULL,30,'men','ELEVATE','Турция','100% лён','Белый',
 true,false,false,true,true,false,ARRAY['лето','новинка'],ARRAY['https://picsum.photos/seed/elevate-m-201/800/1000','https://picsum.photos/seed/elevate-m-201b/800/1000'],
 NOW() - INTERVAL '25 days', NOW()),
('elevate-m-202','Куртка «Trucker Denim»','jacket-trucker-denim','ELV-M-202',
 'Классическая джинсовая куртка trucker из плотного денима. Универсальная вещь на каждый день.',
 'Джинсовая куртка trucker',5990,NULL,24,'men','ELEVATE','Китай','100% хлопок','Синий',
 true,true,true,false,true,false,ARRAY['деним','хит'],ARRAY['https://picsum.photos/seed/elevate-m-202/800/1000','https://picsum.photos/seed/elevate-m-202b/800/1000'],
 NOW() - INTERVAL '37 days', NOW()),
('elevate-m-203','Свитер «Lambswool Crew»','sweater-lambswool-crew','ELV-M-203',
 'Свитер с круглым вырезом из ягнячьей шерсти. Мягкий, тёплый, не колется.',
 'Свитер из ягнячьей шерсти',4990,NULL,28,'men','ELEVATE','Китай','100% шерсть (ламбсвул)','Тёмно-синий',
 true,false,false,false,true,false,ARRAY['зима','базовое'],ARRAY['https://picsum.photos/seed/elevate-m-203/800/1000','https://picsum.photos/seed/elevate-m-203b/800/1000'],
 NOW() - INTERVAL '31 days', NOW()),
('elevate-m-204','Брюки карго «Tactical Cargo»','pants-tactical-cargo','ELV-M-204',
 'Брюки карго с множеством карманов из плотного хлопка. Практичные, прямой крой.',
 'Брюки карго из плотного хлопка',4290,NULL,26,'men','ELEVATE','Вьетнам','97% хлопок, 3% эластан','Хаки',
 true,false,false,false,true,false,ARRAY['базовое'],ARRAY['https://picsum.photos/seed/elevate-m-204/800/1000','https://picsum.photos/seed/elevate-m-204b/800/1000'],
 NOW() - INTERVAL '28 days', NOW()),
('elevate-m-205','Жилет «Down Vest»','vest-down','ELV-M-205',
 'Пуховый жилет с лёгким наполнителем и стойкой. Удобен поверх свитера или рубашки.',
 'Пуховый жилет со стойкой',5490,NULL,22,'men','ELEVATE','Китай','100% полиэстер; наполнитель 80% пух, 20% перо','Чёрный',
 true,false,false,false,true,false,ARRAY['демисезон'],ARRAY['https://picsum.photos/seed/elevate-m-205/800/1000','https://picsum.photos/seed/elevate-m-205b/800/1000'],
 NOW() - INTERVAL '34 days', NOW()),
('elevate-m-206','Поло «LS Polo»','polo-long-sleeve','ELV-M-206',
 'Поло с длинным рукавом из пике. Аккуратный воротник, плотное полотно, для прохладных дней.',
 'Поло с длинным рукавом',2990,NULL,30,'men','ELEVATE','Бангладеш','100% хлопок (пике)','Бордовый',
 true,false,false,false,true,false,ARRAY['демисезон','базовое'],ARRAY['https://picsum.photos/seed/elevate-m-206/800/1000','https://picsum.photos/seed/elevate-m-206b/800/1000'],
 NOW() - INTERVAL '23 days', NOW()),
('elevate-m-207','Пиджак «Unstructured Blazer»','blazer-unstructured','ELV-M-207',
 'Неструктурированный пиджак без жёсткой подкладки. Мягкий, носится как кэжуал поверх футболки.',
 'Неструктурированный пиджак',8990,NULL,16,'men','ELEVATE','Турция','62% полиэстер, 34% вискоза, 4% эластан','Серый',
 true,false,true,false,true,false,ARRAY['офис'],ARRAY['https://picsum.photos/seed/elevate-m-207/800/1000','https://picsum.photos/seed/elevate-m-207b/800/1000'],
 NOW() - INTERVAL '40 days', NOW()),
('elevate-m-208','Худи на молнии «Zip Hoodie»','hoodie-zip','ELV-M-208',
 'Худи на молнии из футера с начёсом. Тёплое, с карманами, капюшон на кулиске.',
 'Худи на молнии с начёсом',3990,NULL,32,'men','ELEVATE','Узбекистан','80% хлопок, 20% полиэстер','Серый меланж',
 true,false,false,false,true,false,ARRAY['базовое','спорт'],ARRAY['https://picsum.photos/seed/elevate-m-208/800/1000','https://picsum.photos/seed/elevate-m-208b/800/1000'],
 NOW() - INTERVAL '20 days', NOW()),
('elevate-m-209','Футболка «Henley Tee»','tee-henley','ELV-M-209',
 'Футболка хенли с планкой на пуговицах из мягкого хлопка. Чуть более интересная, чем базовая.',
 'Футболка хенли с планкой',1990,NULL,40,'men','ELEVATE','Узбекистан','95% хлопок, 5% эластан','Серый',
 true,false,false,false,true,false,ARRAY['базовое'],ARRAY['https://picsum.photos/seed/elevate-m-209/800/1000','https://picsum.photos/seed/elevate-m-209b/800/1000'],
 NOW() - INTERVAL '17 days', NOW()),
('elevate-m-210','Джинсы «Tapered Comfort»','jeans-tapered-comfort','ELV-M-210',
 'Зауженные книзу джинсы с комфортным стрейчем. Свободны в бедре, удобны весь день.',
 'Зауженные джинсы со стрейчем',4990,NULL,32,'men','ELEVATE','Китай','98% хлопок, 2% эластан','Серо-синий',
 true,false,false,false,true,false,ARRAY['деним'],ARRAY['https://picsum.photos/seed/elevate-m-210/800/1000','https://picsum.photos/seed/elevate-m-210b/800/1000'],
 NOW() - INTERVAL '29 days', NOW()),
('elevate-m-211','Парка «Expedition Parka»','parka-expedition','ELV-M-211',
 'Зимняя парка с капюшоном с опушкой и натуральным пухом. Рассчитана на сильные морозы.',
 'Зимняя парка с капюшоном',19990,23990,12,'men','ELEVATE','Китай','Верх 100% полиэстер; наполнитель 85% пух, 15% перо','Хаки',
 true,true,true,true,true,true,ARRAY['зима','хит'],ARRAY['https://picsum.photos/seed/elevate-m-211/800/1000','https://picsum.photos/seed/elevate-m-211b/800/1000'],
 NOW() - INTERVAL '26 days', NOW()),
('elevate-m-212','Свитшот «Graphic Crew»','sweatshirt-graphic-crew','ELV-M-212',
 'Свитшот с минималистичным принтом на груди. Футер с начёсом, прямой крой.',
 'Свитшот с принтом',3490,NULL,30,'men','ELEVATE','Китай','80% хлопок, 20% полиэстер','Чёрный',
 true,false,false,false,true,false,ARRAY['базовое'],ARRAY['https://picsum.photos/seed/elevate-m-212/800/1000','https://picsum.photos/seed/elevate-m-212b/800/1000'],
 NOW() - INTERVAL '22 days', NOW()),
('elevate-m-213','Рубашка «Flannel Overshirt»','shirt-flannel-overshirt','ELV-M-213',
 'Плотная фланелевая рубашка-овершот в клетку. Носится как лёгкая куртка поверх футболки.',
 'Фланелевая рубашка-овершот',4490,NULL,24,'men','ELEVATE','Китай','100% хлопок (фланель)','Сине-зелёная клетка',
 true,false,false,false,true,false,ARRAY['демисезон'],ARRAY['https://picsum.photos/seed/elevate-m-213/800/1000','https://picsum.photos/seed/elevate-m-213b/800/1000'],
 NOW() - INTERVAL '35 days', NOW()),
('elevate-m-214','Шорты «Swim Shorts»','shorts-swim','ELV-M-214',
 'Плавательные шорты из быстросохнущей ткани с сетчатой подкладкой. Удобный пояс на шнурке.',
 'Плавательные шорты',2290,NULL,28,'men','ELEVATE','Вьетнам','100% полиэстер','Тёмно-синий',
 true,false,false,false,true,false,ARRAY['лето'],ARRAY['https://picsum.photos/seed/elevate-m-214/800/1000','https://picsum.photos/seed/elevate-m-214b/800/1000'],
 NOW() - INTERVAL '48 days', NOW()),
('elevate-m-215','Кардиган «Zip Cardigan»','cardigan-zip','ELV-M-215',
 'Трикотажный кардиган на молнии со стойкой. Практичная альтернатива свитеру.',
 'Трикотажный кардиган на молнии',4690,NULL,22,'men','ELEVATE','Китай','60% хлопок, 40% акрил','Тёмно-серый',
 true,false,false,false,true,false,ARRAY['демисезон'],ARRAY['https://picsum.photos/seed/elevate-m-215/800/1000','https://picsum.photos/seed/elevate-m-215b/800/1000'],
 NOW() - INTERVAL '32 days', NOW()),
('elevate-m-216','Брюки «Tech Pants»','pants-tech','ELV-M-216',
 'Технологичные брюки из эластичной ткани с водоотталкивающей пропиткой. Удобны в движении.',
 'Технологичные эластичные брюки',5290,NULL,24,'men','ELEVATE','Вьетнам','88% полиамид, 12% эластан','Чёрный',
 true,false,false,true,true,false,ARRAY['спорт','новинка'],ARRAY['https://picsum.photos/seed/elevate-m-216/800/1000','https://picsum.photos/seed/elevate-m-216b/800/1000'],
 NOW() - INTERVAL '13 days', NOW()),
('elevate-m-217','Тренч «Mac Coat»','coat-mac','ELV-M-217',
 'Мужской тренч прямого силуэта с потайной застёжкой. Лёгкая водоотталкивающая ткань.',
 'Мужской тренч прямого кроя',12990,NULL,14,'men','ELEVATE','Китай','65% хлопок, 35% полиэстер','Бежевый',
 true,false,true,false,true,false,ARRAY['демисезон','офис'],ARRAY['https://picsum.photos/seed/elevate-m-217/800/1000','https://picsum.photos/seed/elevate-m-217b/800/1000'],
 NOW() - INTERVAL '41 days', NOW()),
('elevate-m-218','Лонгслив «Long Sleeve Tee»','longsleeve-basic','ELV-M-218',
 'Базовый лонгслив из плотного хлопка. Не просвечивает, хорошо тянется, держит форму.',
 'Базовый лонгслив',1790,NULL,42,'men','ELEVATE','Узбекистан','95% хлопок, 5% эластан','Белый',
 true,false,false,false,true,false,ARRAY['базовое'],ARRAY['https://picsum.photos/seed/elevate-m-218/800/1000','https://picsum.photos/seed/elevate-m-218b/800/1000'],
 NOW() - INTERVAL '19 days', NOW()),
('elevate-m-219','Джемпер «Half-Zip Knit»','sweater-half-zip','ELV-M-219',
 'Трикотажный джемпер с воротником на короткой молнии. Тёплый, аккуратный, на каждый день.',
 'Джемпер с короткой молнией',4290,NULL,26,'men','ELEVATE','Китай','50% хлопок, 50% акрил','Овсяный',
 true,false,false,false,true,false,ARRAY['демисезон','базовое'],ARRAY['https://picsum.photos/seed/elevate-m-219/800/1000','https://picsum.photos/seed/elevate-m-219b/800/1000'],
 NOW() - INTERVAL '24 days', NOW()),
('elevate-m-220','Куртка-рубашка «Wool Overshirt»','jacket-wool-overshirt','ELV-M-220',
 'Тёплая куртка-рубашка из шерстяного сукна. Носится поверх футболки в прохладную погоду.',
 'Куртка-рубашка из сукна',6990,NULL,20,'men','ELEVATE','Китай','60% шерсть, 40% полиэстер','Серый',
 true,false,false,true,true,false,ARRAY['зима','новинка'],ARRAY['https://picsum.photos/seed/elevate-m-220/800/1000','https://picsum.photos/seed/elevate-m-220b/800/1000'],
 NOW() - INTERVAL '15 days', NOW()),
('elevate-m-221','Поло «Tipped Polo»','polo-tipped','ELV-M-221',
 'Поло из пике с контрастной окантовкой воротника и манжет. Аккуратная деталь к классике.',
 'Поло с контрастной окантовкой',2690,NULL,30,'men','ELEVATE','Бангладеш','100% хлопок (пике)','Белый',
 true,false,false,false,true,false,ARRAY['лето','базовое'],ARRAY['https://picsum.photos/seed/elevate-m-221/800/1000','https://picsum.photos/seed/elevate-m-221b/800/1000'],
 NOW() - INTERVAL '46 days', NOW()),
('elevate-m-222','Ветровка «Coach Jacket»','jacket-coach','ELV-M-222',
 'Лёгкая куртка-coach на кнопках с подкладкой. Защищает от ветра, минималистичный дизайн.',
 'Лёгкая куртка-coach на кнопках',4490,NULL,24,'men','ELEVATE','Китай','100% полиэстер','Чёрный',
 true,false,false,false,true,false,ARRAY['демисезон'],ARRAY['https://picsum.photos/seed/elevate-m-222/800/1000','https://picsum.photos/seed/elevate-m-222b/800/1000'],
 NOW() - INTERVAL '38 days', NOW())
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- 2. ФОТО (главное + второй кадр; цветовые варианты у 5 моделей)
-- ============================================================================
INSERT INTO product_images (id, product_id, url, alt_text, sort_order, is_primary, media_type, color) VALUES
  ('pi2-w-201-1','elevate-w-201','https://picsum.photos/seed/elevate-w-201/800/1000','Платье Linen Shirt',0,true,'image',NULL),
  ('pi2-w-201-2','elevate-w-201','https://picsum.photos/seed/elevate-w-201b/800/1000','Платье Linen Shirt деталь',1,false,'image',NULL),
  ('pi2-w-202-1','elevate-w-202','https://picsum.photos/seed/elevate-w-202/800/1000','Платье Velvet Night',0,true,'image','Бордовый'),
  ('pi2-w-202-2','elevate-w-202','https://picsum.photos/seed/elevate-w-202b/800/1000','Платье Velvet Night спина',1,false,'image','Бордовый'),
  ('pi2-w-202-3','elevate-w-202','https://picsum.photos/seed/elevate-w-202c/800/1000','Платье Velvet чёрное',2,false,'image','Чёрный'),
  ('pi2-w-203-1','elevate-w-203','https://picsum.photos/seed/elevate-w-203/800/1000','Топ Bardot',0,true,'image',NULL),
  ('pi2-w-203-2','elevate-w-203','https://picsum.photos/seed/elevate-w-203b/800/1000','Топ Bardot деталь',1,false,'image',NULL),
  ('pi2-w-204-1','elevate-w-204','https://picsum.photos/seed/elevate-w-204/800/1000','Юбка Satin Slip',0,true,'image',NULL),
  ('pi2-w-204-2','elevate-w-204','https://picsum.photos/seed/elevate-w-204b/800/1000','Юбка Satin Slip деталь',1,false,'image',NULL),
  ('pi2-w-205-1','elevate-w-205','https://picsum.photos/seed/elevate-w-205/800/1000','Джинсы Flare 70s',0,true,'image',NULL),
  ('pi2-w-205-2','elevate-w-205','https://picsum.photos/seed/elevate-w-205b/800/1000','Джинсы Flare 70s деталь',1,false,'image',NULL),
  ('pi2-w-206-1','elevate-w-206','https://picsum.photos/seed/elevate-w-206/800/1000','Кейп-пальто',0,true,'image',NULL),
  ('pi2-w-206-2','elevate-w-206','https://picsum.photos/seed/elevate-w-206b/800/1000','Кейп-пальто деталь',1,false,'image',NULL),
  ('pi2-w-207-1','elevate-w-207','https://picsum.photos/seed/elevate-w-207/800/1000','Косуха Biker Lux',0,true,'image','Чёрный'),
  ('pi2-w-207-2','elevate-w-207','https://picsum.photos/seed/elevate-w-207b/800/1000','Косуха Biker Lux деталь',1,false,'image','Чёрный'),
  ('pi2-w-207-3','elevate-w-207','https://picsum.photos/seed/elevate-w-207c/800/1000','Косуха коричневая',2,false,'image','Коричневый'),
  ('pi2-w-208-1','elevate-w-208','https://picsum.photos/seed/elevate-w-208/800/1000','Водолазка Merino',0,true,'image',NULL),
  ('pi2-w-208-2','elevate-w-208','https://picsum.photos/seed/elevate-w-208b/800/1000','Водолазка Merino деталь',1,false,'image',NULL),
  ('pi2-w-209-1','elevate-w-209','https://picsum.photos/seed/elevate-w-209/800/1000','Жилет Tailored',0,true,'image',NULL),
  ('pi2-w-209-2','elevate-w-209','https://picsum.photos/seed/elevate-w-209b/800/1000','Жилет Tailored деталь',1,false,'image',NULL),
  ('pi2-w-210-1','elevate-w-210','https://picsum.photos/seed/elevate-w-210/800/1000','Платье-футляр',0,true,'image',NULL),
  ('pi2-w-210-2','elevate-w-210','https://picsum.photos/seed/elevate-w-210b/800/1000','Платье-футляр деталь',1,false,'image',NULL),
  ('pi2-w-211-1','elevate-w-211','https://picsum.photos/seed/elevate-w-211/800/1000','Свитер Chunky',0,true,'image',NULL),
  ('pi2-w-211-2','elevate-w-211','https://picsum.photos/seed/elevate-w-211b/800/1000','Свитер Chunky фактура',1,false,'image',NULL),
  ('pi2-w-212-1','elevate-w-212','https://picsum.photos/seed/elevate-w-212/800/1000','Майка Silk Cami',0,true,'image',NULL),
  ('pi2-w-212-2','elevate-w-212','https://picsum.photos/seed/elevate-w-212b/800/1000','Майка Silk Cami деталь',1,false,'image',NULL),
  ('pi2-w-213-1','elevate-w-213','https://picsum.photos/seed/elevate-w-213/800/1000','Брюки палаццо',0,true,'image',NULL),
  ('pi2-w-213-2','elevate-w-213','https://picsum.photos/seed/elevate-w-213b/800/1000','Брюки палаццо деталь',1,false,'image',NULL),
  ('pi2-w-214-1','elevate-w-214','https://picsum.photos/seed/elevate-w-214/800/1000','Комбинезон Utility',0,true,'image',NULL),
  ('pi2-w-214-2','elevate-w-214','https://picsum.photos/seed/elevate-w-214b/800/1000','Комбинезон Utility деталь',1,false,'image',NULL),
  ('pi2-w-215-1','elevate-w-215','https://picsum.photos/seed/elevate-w-215/800/1000','Кардиган Long Line',0,true,'image',NULL),
  ('pi2-w-215-2','elevate-w-215','https://picsum.photos/seed/elevate-w-215b/800/1000','Кардиган Long Line деталь',1,false,'image',NULL),
  ('pi2-w-216-1','elevate-w-216','https://picsum.photos/seed/elevate-w-216/800/1000','Блейзер Boyfriend',0,true,'image',NULL),
  ('pi2-w-216-2','elevate-w-216','https://picsum.photos/seed/elevate-w-216b/800/1000','Блейзер Boyfriend деталь',1,false,'image',NULL),
  ('pi2-w-217-1','elevate-w-217','https://picsum.photos/seed/elevate-w-217/800/1000','Юбка Denim A-line',0,true,'image',NULL),
  ('pi2-w-217-2','elevate-w-217','https://picsum.photos/seed/elevate-w-217b/800/1000','Юбка Denim A-line деталь',1,false,'image',NULL),
  ('pi2-w-218-1','elevate-w-218','https://picsum.photos/seed/elevate-w-218/800/1000','Платье Polka Tea',0,true,'image',NULL),
  ('pi2-w-218-2','elevate-w-218','https://picsum.photos/seed/elevate-w-218b/800/1000','Платье Polka Tea деталь',1,false,'image',NULL),
  ('pi2-w-219-1','elevate-w-219','https://picsum.photos/seed/elevate-w-219/800/1000','Пальто Quilted',0,true,'image','Чёрный'),
  ('pi2-w-219-2','elevate-w-219','https://picsum.photos/seed/elevate-w-219b/800/1000','Пальто Quilted капюшон',1,false,'image','Чёрный'),
  ('pi2-w-219-3','elevate-w-219','https://picsum.photos/seed/elevate-w-219c/800/1000','Пальто оливковое',2,false,'image','Оливковый'),
  ('pi2-w-220-1','elevate-w-220','https://picsum.photos/seed/elevate-w-220/800/1000','Худи Crop',0,true,'image',NULL),
  ('pi2-w-220-2','elevate-w-220','https://picsum.photos/seed/elevate-w-220b/800/1000','Худи Crop деталь',1,false,'image',NULL),
  ('pi2-w-221-1','elevate-w-221','https://picsum.photos/seed/elevate-w-221/800/1000','Джоггеры Soft',0,true,'image',NULL),
  ('pi2-w-221-2','elevate-w-221','https://picsum.photos/seed/elevate-w-221b/800/1000','Джоггеры Soft деталь',1,false,'image',NULL),
  ('pi2-w-222-1','elevate-w-222','https://picsum.photos/seed/elevate-w-222/800/1000','Рубашка Flannel',0,true,'image',NULL),
  ('pi2-w-222-2','elevate-w-222','https://picsum.photos/seed/elevate-w-222b/800/1000','Рубашка Flannel деталь',1,false,'image',NULL),
  ('pi2-w-223-1','elevate-w-223','https://picsum.photos/seed/elevate-w-223/800/1000','Бомбер Satin',0,true,'image',NULL),
  ('pi2-w-223-2','elevate-w-223','https://picsum.photos/seed/elevate-w-223b/800/1000','Бомбер Satin вышивка',1,false,'image',NULL),
  ('pi2-w-224-1','elevate-w-224','https://picsum.photos/seed/elevate-w-224/800/1000','Юбка Pleated Maxi',0,true,'image',NULL),
  ('pi2-w-224-2','elevate-w-224','https://picsum.photos/seed/elevate-w-224b/800/1000','Юбка Pleated Maxi деталь',1,false,'image',NULL),
  ('pi2-w-225-1','elevate-w-225','https://picsum.photos/seed/elevate-w-225/800/1000','Жакет Linen',0,true,'image',NULL),
  ('pi2-w-225-2','elevate-w-225','https://picsum.photos/seed/elevate-w-225b/800/1000','Жакет Linen деталь',1,false,'image',NULL),
  ('pi2-w-226-1','elevate-w-226','https://picsum.photos/seed/elevate-w-226/800/1000','Платье Ribbed',0,true,'image',NULL),
  ('pi2-w-226-2','elevate-w-226','https://picsum.photos/seed/elevate-w-226b/800/1000','Платье Ribbed деталь',1,false,'image',NULL),
  ('pi2-m-201-1','elevate-m-201','https://picsum.photos/seed/elevate-m-201/800/1000','Рубашка Linen Resort',0,true,'image',NULL),
  ('pi2-m-201-2','elevate-m-201','https://picsum.photos/seed/elevate-m-201b/800/1000','Рубашка Linen Resort деталь',1,false,'image',NULL),
  ('pi2-m-202-1','elevate-m-202','https://picsum.photos/seed/elevate-m-202/800/1000','Куртка Trucker',0,true,'image','Синий'),
  ('pi2-m-202-2','elevate-m-202','https://picsum.photos/seed/elevate-m-202b/800/1000','Куртка Trucker деталь',1,false,'image','Синий'),
  ('pi2-m-202-3','elevate-m-202','https://picsum.photos/seed/elevate-m-202c/800/1000','Куртка Trucker чёрная',2,false,'image','Чёрный'),
  ('pi2-m-203-1','elevate-m-203','https://picsum.photos/seed/elevate-m-203/800/1000','Свитер Lambswool',0,true,'image',NULL),
  ('pi2-m-203-2','elevate-m-203','https://picsum.photos/seed/elevate-m-203b/800/1000','Свитер Lambswool фактура',1,false,'image',NULL),
  ('pi2-m-204-1','elevate-m-204','https://picsum.photos/seed/elevate-m-204/800/1000','Брюки карго',0,true,'image',NULL),
  ('pi2-m-204-2','elevate-m-204','https://picsum.photos/seed/elevate-m-204b/800/1000','Брюки карго карманы',1,false,'image',NULL),
  ('pi2-m-205-1','elevate-m-205','https://picsum.photos/seed/elevate-m-205/800/1000','Жилет Down',0,true,'image',NULL),
  ('pi2-m-205-2','elevate-m-205','https://picsum.photos/seed/elevate-m-205b/800/1000','Жилет Down деталь',1,false,'image',NULL),
  ('pi2-m-206-1','elevate-m-206','https://picsum.photos/seed/elevate-m-206/800/1000','Поло LS',0,true,'image',NULL),
  ('pi2-m-206-2','elevate-m-206','https://picsum.photos/seed/elevate-m-206b/800/1000','Поло LS воротник',1,false,'image',NULL),
  ('pi2-m-207-1','elevate-m-207','https://picsum.photos/seed/elevate-m-207/800/1000','Пиджак Unstructured',0,true,'image',NULL),
  ('pi2-m-207-2','elevate-m-207','https://picsum.photos/seed/elevate-m-207b/800/1000','Пиджак Unstructured деталь',1,false,'image',NULL),
  ('pi2-m-208-1','elevate-m-208','https://picsum.photos/seed/elevate-m-208/800/1000','Худи Zip',0,true,'image',NULL),
  ('pi2-m-208-2','elevate-m-208','https://picsum.photos/seed/elevate-m-208b/800/1000','Худи Zip деталь',1,false,'image',NULL),
  ('pi2-m-209-1','elevate-m-209','https://picsum.photos/seed/elevate-m-209/800/1000','Футболка Henley',0,true,'image',NULL),
  ('pi2-m-209-2','elevate-m-209','https://picsum.photos/seed/elevate-m-209b/800/1000','Футболка Henley планка',1,false,'image',NULL),
  ('pi2-m-210-1','elevate-m-210','https://picsum.photos/seed/elevate-m-210/800/1000','Джинсы Tapered',0,true,'image',NULL),
  ('pi2-m-210-2','elevate-m-210','https://picsum.photos/seed/elevate-m-210b/800/1000','Джинсы Tapered деталь',1,false,'image',NULL),
  ('pi2-m-211-1','elevate-m-211','https://picsum.photos/seed/elevate-m-211/800/1000','Парка Expedition',0,true,'image','Хаки'),
  ('pi2-m-211-2','elevate-m-211','https://picsum.photos/seed/elevate-m-211b/800/1000','Парка Expedition капюшон',1,false,'image','Хаки'),
  ('pi2-m-211-3','elevate-m-211','https://picsum.photos/seed/elevate-m-211c/800/1000','Парка чёрная',2,false,'image','Чёрный'),
  ('pi2-m-212-1','elevate-m-212','https://picsum.photos/seed/elevate-m-212/800/1000','Свитшот Graphic',0,true,'image',NULL),
  ('pi2-m-212-2','elevate-m-212','https://picsum.photos/seed/elevate-m-212b/800/1000','Свитшот Graphic принт',1,false,'image',NULL),
  ('pi2-m-213-1','elevate-m-213','https://picsum.photos/seed/elevate-m-213/800/1000','Рубашка Overshirt',0,true,'image',NULL),
  ('pi2-m-213-2','elevate-m-213','https://picsum.photos/seed/elevate-m-213b/800/1000','Рубашка Overshirt деталь',1,false,'image',NULL),
  ('pi2-m-214-1','elevate-m-214','https://picsum.photos/seed/elevate-m-214/800/1000','Шорты Swim',0,true,'image',NULL),
  ('pi2-m-214-2','elevate-m-214','https://picsum.photos/seed/elevate-m-214b/800/1000','Шорты Swim деталь',1,false,'image',NULL),
  ('pi2-m-215-1','elevate-m-215','https://picsum.photos/seed/elevate-m-215/800/1000','Кардиган Zip',0,true,'image',NULL),
  ('pi2-m-215-2','elevate-m-215','https://picsum.photos/seed/elevate-m-215b/800/1000','Кардиган Zip деталь',1,false,'image',NULL),
  ('pi2-m-216-1','elevate-m-216','https://picsum.photos/seed/elevate-m-216/800/1000','Брюки Tech',0,true,'image',NULL),
  ('pi2-m-216-2','elevate-m-216','https://picsum.photos/seed/elevate-m-216b/800/1000','Брюки Tech деталь',1,false,'image',NULL),
  ('pi2-m-217-1','elevate-m-217','https://picsum.photos/seed/elevate-m-217/800/1000','Тренч Mac',0,true,'image',NULL),
  ('pi2-m-217-2','elevate-m-217','https://picsum.photos/seed/elevate-m-217b/800/1000','Тренч Mac деталь',1,false,'image',NULL),
  ('pi2-m-218-1','elevate-m-218','https://picsum.photos/seed/elevate-m-218/800/1000','Лонгслив базовый',0,true,'image',NULL),
  ('pi2-m-218-2','elevate-m-218','https://picsum.photos/seed/elevate-m-218b/800/1000','Лонгслив базовый деталь',1,false,'image',NULL),
  ('pi2-m-219-1','elevate-m-219','https://picsum.photos/seed/elevate-m-219/800/1000','Джемпер Half-Zip',0,true,'image',NULL),
  ('pi2-m-219-2','elevate-m-219','https://picsum.photos/seed/elevate-m-219b/800/1000','Джемпер Half-Zip деталь',1,false,'image',NULL),
  ('pi2-m-220-1','elevate-m-220','https://picsum.photos/seed/elevate-m-220/800/1000','Куртка-рубашка Wool',0,true,'image',NULL),
  ('pi2-m-220-2','elevate-m-220','https://picsum.photos/seed/elevate-m-220b/800/1000','Куртка-рубашка Wool деталь',1,false,'image',NULL),
  ('pi2-m-221-1','elevate-m-221','https://picsum.photos/seed/elevate-m-221/800/1000','Поло Tipped',0,true,'image',NULL),
  ('pi2-m-221-2','elevate-m-221','https://picsum.photos/seed/elevate-m-221b/800/1000','Поло Tipped воротник',1,false,'image',NULL),
  ('pi2-m-222-1','elevate-m-222','https://picsum.photos/seed/elevate-m-222/800/1000','Куртка Coach',0,true,'image',NULL),
  ('pi2-m-222-2','elevate-m-222','https://picsum.photos/seed/elevate-m-222b/800/1000','Куртка Coach деталь',1,false,'image',NULL)
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- 3. СВЯЗИ ТОВАР ↔ КАТЕГОРИЯ
-- ============================================================================
INSERT INTO product_category (id, product_id, category_id) VALUES
  ('pc2-w-201','elevate-w-201','women'),('pc2-w-202','elevate-w-202','women'),
  ('pc2-w-203','elevate-w-203','women'),('pc2-w-204','elevate-w-204','women'),
  ('pc2-w-205','elevate-w-205','women'),('pc2-w-206','elevate-w-206','women'),
  ('pc2-w-207','elevate-w-207','women'),('pc2-w-208','elevate-w-208','women'),
  ('pc2-w-209','elevate-w-209','women'),('pc2-w-210','elevate-w-210','women'),
  ('pc2-w-211','elevate-w-211','women'),('pc2-w-212','elevate-w-212','women'),
  ('pc2-w-213','elevate-w-213','women'),('pc2-w-214','elevate-w-214','women'),
  ('pc2-w-215','elevate-w-215','women'),('pc2-w-216','elevate-w-216','women'),
  ('pc2-w-217','elevate-w-217','women'),('pc2-w-218','elevate-w-218','women'),
  ('pc2-w-219','elevate-w-219','women'),('pc2-w-220','elevate-w-220','women'),
  ('pc2-w-221','elevate-w-221','women'),('pc2-w-222','elevate-w-222','women'),
  ('pc2-w-223','elevate-w-223','women'),('pc2-w-224','elevate-w-224','women'),
  ('pc2-w-225','elevate-w-225','women'),('pc2-w-226','elevate-w-226','women'),
  ('pc2-m-201','elevate-m-201','men'),('pc2-m-202','elevate-m-202','men'),
  ('pc2-m-203','elevate-m-203','men'),('pc2-m-204','elevate-m-204','men'),
  ('pc2-m-205','elevate-m-205','men'),('pc2-m-206','elevate-m-206','men'),
  ('pc2-m-207','elevate-m-207','men'),('pc2-m-208','elevate-m-208','men'),
  ('pc2-m-209','elevate-m-209','men'),('pc2-m-210','elevate-m-210','men'),
  ('pc2-m-211','elevate-m-211','men'),('pc2-m-212','elevate-m-212','men'),
  ('pc2-m-213','elevate-m-213','men'),('pc2-m-214','elevate-m-214','men'),
  ('pc2-m-215','elevate-m-215','men'),('pc2-m-216','elevate-m-216','men'),
  ('pc2-m-217','elevate-m-217','men'),('pc2-m-218','elevate-m-218','men'),
  ('pc2-m-219','elevate-m-219','men'),('pc2-m-220','elevate-m-220','men'),
  ('pc2-m-221','elevate-m-221','men'),('pc2-m-222','elevate-m-222','men'),
  -- новинки
  ('pc2-n-w201','elevate-w-201','new'),('pc2-n-w209','elevate-w-209','new'),
  ('pc2-n-w214','elevate-w-214','new'),('pc2-n-w218','elevate-w-218','new'),
  ('pc2-n-w219','elevate-w-219','new'),('pc2-n-w223','elevate-w-223','new'),
  ('pc2-n-m201','elevate-m-201','new'),('pc2-n-m211','elevate-m-211','new'),
  ('pc2-n-m216','elevate-m-216','new'),('pc2-n-m220','elevate-m-220','new'),
  -- коллекции
  ('pc2-c-w202','elevate-w-202','collections'),('pc2-c-w207','elevate-w-207','collections'),
  ('pc2-c-w216','elevate-w-216','collections'),('pc2-c-w219','elevate-w-219','collections'),
  ('pc2-c-m202','elevate-m-202','collections'),('pc2-c-m207','elevate-m-207','collections'),
  ('pc2-c-m211','elevate-m-211','collections'),('pc2-c-m217','elevate-m-217','collections')
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- 4. НОВЫЕ ПОЛЬЗОВАТЕЛИ (user-041..085) + профили
-- ============================================================================
INSERT INTO users (id, name, email, password, email_verified, role, status, is_verified, created_at, updated_at) VALUES
  ('user-041','Алёна Журавлёва','alena.zhuravleva@yandex.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '95 days','user','active',true, NOW() - INTERVAL '96 days', NOW()),
  ('user-042','Глеб Зуев','gleb.zuev@gmail.com','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '92 days','user','active',true, NOW() - INTERVAL '93 days', NOW()),
  ('user-043','Кристина Лазарева','kristina.lazareva@mail.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '89 days','user','active',false, NOW() - INTERVAL '90 days', NOW()),
  ('user-044','Руслан Гордеев','ruslan.gordeev@yandex.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '86 days','user','active',true, NOW() - INTERVAL '87 days', NOW()),
  ('user-045','Оксана Дроздова','oksana.drozdova@gmail.com','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '83 days','user','active',true, NOW() - INTERVAL '84 days', NOW()),
  ('user-046','Артур Богомолов','artur.bogomolov@mail.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '80 days','user','active',false, NOW() - INTERVAL '81 days', NOW()),
  ('user-047','Лариса Фомина','larisa.fomina@yandex.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '77 days','user','active',true, NOW() - INTERVAL '78 days', NOW()),
  ('user-048','Вадим Шестаков','vadim.shestakov@gmail.com','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '74 days','user','active',true, NOW() - INTERVAL '75 days', NOW()),
  ('user-049','Жанна Тарасова','zhanna.tarasova@mail.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '71 days','user','active',false, NOW() - INTERVAL '72 days', NOW()),
  ('user-050','Леонид Карпов','leonid.karpov@yandex.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '68 days','user','active',true, NOW() - INTERVAL '69 days', NOW()),
  ('user-051','Снежана Громова','snezhana.gromova@gmail.com','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '65 days','user','active',true, NOW() - INTERVAL '66 days', NOW()),
  ('user-052','Борис Якушев','boris.yakushev@mail.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '62 days','user','active',false, NOW() - INTERVAL '63 days', NOW()),
  ('user-053','Анжела Соболева','anzhela.soboleva@yandex.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '59 days','user','active',true, NOW() - INTERVAL '60 days', NOW()),
  ('user-054','Виталий Прохоров','vitaly.prokhorov@gmail.com','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '56 days','user','active',true, NOW() - INTERVAL '57 days', NOW()),
  ('user-055','Регина Беляева','regina.belyaeva@mail.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '53 days','user','active',false, NOW() - INTERVAL '54 days', NOW()),
  ('user-056','Геннадий Мельников','gennady.melnikov@yandex.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '50 days','user','active',true, NOW() - INTERVAL '51 days', NOW()),
  ('user-057','Эльвира Носова','elvira.nosova@gmail.com','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '47 days','user','active',true, NOW() - INTERVAL '48 days', NOW()),
  ('user-058','Семён Воронов','semen.voronov@mail.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '44 days','user','active',false, NOW() - INTERVAL '45 days', NOW()),
  ('user-059','Динара Юсупова','dinara.yusupova@yandex.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '41 days','user','active',true, NOW() - INTERVAL '42 days', NOW()),
  ('user-060','Аркадий Поляков','arkady.polyakov@gmail.com','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '38 days','user','active',true, NOW() - INTERVAL '39 days', NOW()),
  ('user-061','Яна Циммерман','yana.zimmerman@mail.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '36 days','user','active',false, NOW() - INTERVAL '37 days', NOW()),
  ('user-062','Тарас Лукин','taras.lukin@yandex.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '34 days','user','active',true, NOW() - INTERVAL '35 days', NOW()),
  ('user-063','Инна Зотова','inna.zotova@gmail.com','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '32 days','user','active',true, NOW() - INTERVAL '33 days', NOW()),
  ('user-064','Филипп Гаврилов','filipp.gavrilov@mail.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '30 days','user','active',false, NOW() - INTERVAL '31 days', NOW()),
  ('user-065','Алла Шубина','alla.shubina@yandex.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '28 days','user','active',true, NOW() - INTERVAL '29 days', NOW()),
  ('user-066','Захар Титов','zakhar.titov@gmail.com','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '26 days','user','active',true, NOW() - INTERVAL '27 days', NOW()),
  ('user-067','Майя Логинова','maya.loginova@mail.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '24 days','user','active',false, NOW() - INTERVAL '25 days', NOW()),
  ('user-068','Назар Колесников','nazar.kolesnikov@yandex.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '22 days','user','active',true, NOW() - INTERVAL '23 days', NOW()),
  ('user-069','Galina Sergeeva','galina.sergeeva@gmail.com','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '20 days','user','active',true, NOW() - INTERVAL '21 days', NOW()),
  ('user-070','Игнат Фролов','ignat.frolov@mail.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '18 days','user','active',false, NOW() - INTERVAL '19 days', NOW()),
  ('user-071','Диана Маслова','diana.maslova@yandex.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '16 days','user','active',true, NOW() - INTERVAL '17 days', NOW()),
  ('user-072','Мирон Савельев','miron.savelev@gmail.com','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '15 days','user','active',true, NOW() - INTERVAL '16 days', NOW()),
  ('user-073','Лидия Антонова','lidiya.antonova@mail.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '14 days','user','active',false, NOW() - INTERVAL '15 days', NOW()),
  ('user-074','Святослав Гущин','svyatoslav.gushchin@yandex.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '13 days','user','active',true, NOW() - INTERVAL '14 days', NOW()),
  ('user-075','Нина Беляк','nina.belyak@gmail.com','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '12 days','user','active',true, NOW() - INTERVAL '13 days', NOW()),
  ('user-076','Богдан Овсянников','bogdan.ovsyannikov@mail.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '11 days','user','active',false, NOW() - INTERVAL '12 days', NOW()),
  ('user-077','Эмма Гончарова','emma.goncharova@yandex.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '10 days','user','active',true, NOW() - INTERVAL '11 days', NOW()),
  ('user-078','Тихон Дьяконов','tikhon.dyakonov@gmail.com','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '9 days','user','active',true, NOW() - INTERVAL '10 days', NOW()),
  ('user-079','Влада Киреева','vlada.kireeva@mail.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '8 days','user','active',false, NOW() - INTERVAL '9 days', NOW()),
  ('user-080','Эдуард Панфилов','eduard.panfilov@yandex.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '7 days','user','active',true, NOW() - INTERVAL '8 days', NOW()),
  ('user-081','Камилла Носкова','kamilla.noskova@gmail.com','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '6 days','user','active',true, NOW() - INTERVAL '7 days', NOW()),
  ('user-082','Марат Хабибуллин','marat.khabibullin@mail.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '5 days','user','active',false, NOW() - INTERVAL '6 days', NOW()),
  ('user-083','Олеся Кудрявцева','olesya.kudryavtseva@yandex.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '4 days','user','active',true, NOW() - INTERVAL '5 days', NOW()),
  ('user-084','Вячеслав Игнатов','vyacheslav.ignatov@gmail.com','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '3 days','user','active',true, NOW() - INTERVAL '4 days', NOW()),
  ('user-085','Таисия Ермакова','taisiya.ermakova@mail.ru','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',NOW() - INTERVAL '2 days','user','active',true, NOW() - INTERVAL '3 days', NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO user_profiles (id, user_id, first_name, last_name, phone, address) VALUES
  ('up-041','user-041','Алёна','Журавлёва','+7 (952) 345-68-41','г. Москва'),
  ('up-042','user-042','Глеб','Зуев','+7 (953) 345-68-42','г. Санкт-Петербург'),
  ('up-043','user-043','Кристина','Лазарева','+7 (954) 345-68-43','г. Новосибирск'),
  ('up-044','user-044','Руслан','Гордеев','+7 (955) 345-68-44','г. Казань'),
  ('up-045','user-045','Оксана','Дроздова','+7 (956) 345-68-45','г. Екатеринбург'),
  ('up-046','user-046','Артур','Богомолов','+7 (957) 345-68-46','г. Нижний Новгород'),
  ('up-047','user-047','Лариса','Фомина','+7 (958) 345-68-47','г. Краснодар'),
  ('up-048','user-048','Вадим','Шестаков','+7 (959) 345-68-48','г. Самара'),
  ('up-049','user-049','Жанна','Тарасова','+7 (960) 345-68-49','г. Уфа'),
  ('up-050','user-050','Леонид','Карпов','+7 (961) 345-68-50','г. Ростов-на-Дону'),
  ('up-051','user-051','Снежана','Громова','+7 (962) 345-68-51','г. Пермь'),
  ('up-052','user-052','Борис','Якушев','+7 (963) 345-68-52','г. Челябинск'),
  ('up-053','user-053','Анжела','Соболева','+7 (964) 345-68-53','г. Воронеж'),
  ('up-054','user-054','Виталий','Прохоров','+7 (965) 345-68-54','г. Волгоград'),
  ('up-055','user-055','Регина','Беляева','+7 (966) 345-68-55','г. Тюмень'),
  ('up-056','user-056','Геннадий','Мельников','+7 (967) 345-68-56','г. Саратов'),
  ('up-057','user-057','Эльвира','Носова','+7 (968) 345-68-57','г. Тольятти'),
  ('up-058','user-058','Семён','Воронов','+7 (969) 345-68-58','г. Ижевск'),
  ('up-059','user-059','Динара','Юсупова','+7 (970) 345-68-59','г. Казань'),
  ('up-060','user-060','Аркадий','Поляков','+7 (971) 345-68-60','г. Барнаул'),
  ('up-061','user-061','Яна','Циммерман','+7 (972) 345-68-61','г. Калининград'),
  ('up-062','user-062','Тарас','Лукин','+7 (973) 345-68-62','г. Иркутск'),
  ('up-063','user-063','Инна','Зотова','+7 (974) 345-68-63','г. Хабаровск'),
  ('up-064','user-064','Филипп','Гаврилов','+7 (975) 345-68-64','г. Ярославль'),
  ('up-065','user-065','Алла','Шубина','+7 (976) 345-68-65','г. Владивосток'),
  ('up-066','user-066','Захар','Титов','+7 (977) 345-68-66','г. Томск'),
  ('up-067','user-067','Майя','Логинова','+7 (978) 345-68-67','г. Оренбург'),
  ('up-068','user-068','Назар','Колесников','+7 (979) 345-68-68','г. Кемерово'),
  ('up-069','user-069','Галина','Сергеева','+7 (980) 345-68-69','г. Рязань'),
  ('up-070','user-070','Игнат','Фролов','+7 (981) 345-68-70','г. Тула'),
  ('up-071','user-071','Диана','Маслова','+7 (982) 345-68-71','г. Липецк'),
  ('up-072','user-072','Мирон','Савельев','+7 (983) 345-68-72','г. Киров'),
  ('up-073','user-073','Лидия','Антонова','+7 (984) 345-68-73','г. Чебоксары'),
  ('up-074','user-074','Святослав','Гущин','+7 (985) 345-68-74','г. Сочи'),
  ('up-075','user-075','Нина','Беляк','+7 (986) 345-68-75','г. Брянск'),
  ('up-076','user-076','Богдан','Овсянников','+7 (987) 345-68-76','г. Курск'),
  ('up-077','user-077','Эмма','Гончарова','+7 (988) 345-68-77','г. Москва'),
  ('up-078','user-078','Тихон','Дьяконов','+7 (989) 345-68-78','г. Санкт-Петербург'),
  ('up-079','user-079','Влада','Киреева','+7 (990) 345-68-79','г. Тверь'),
  ('up-080','user-080','Эдуард','Панфилов','+7 (991) 345-68-80','г. Псков'),
  ('up-081','user-081','Камилла','Носкова','+7 (992) 345-68-81','г. Смоленск'),
  ('up-082','user-082','Марат','Хабибуллин','+7 (993) 345-68-82','г. Набережные Челны'),
  ('up-083','user-083','Олеся','Кудрявцева','+7 (994) 345-68-83','г. Вологда'),
  ('up-084','user-084','Вячеслав','Игнатов','+7 (995) 345-68-84','г. Архангельск'),
  ('up-085','user-085','Таисия','Ермакова','+7 (996) 345-68-85','г. Мурманск')
ON CONFLICT (user_id) DO NOTHING;

-- ============================================================================
-- 5. ОТЗЫВЫ (rev-201..356) — все уникальные, is_approved=true, locale='ru'.
--    Авторы — смесь новых (user-041..085) и существующих покупателей.
-- ============================================================================
INSERT INTO reviews (id, user_id, product_id, rating, title, comment, is_verified_purchase, is_approved, helpful_count, locale, admin_response, admin_responded_at, created_at, updated_at) VALUES
-- w-201 Linen Shirt (5)
('rev-201','user-041','elevate-w-201',5,'Лён мечты','Платье дышит, в жару спасает. Лён плотный, не просвечивает, цвет оливковый очень благородный.',true,true,12,'ru',NULL,NULL,NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days'),
('rev-202','user-007','elevate-w-201',4,'Хорошее, но мнётся','Как любой лён — мнётся, но это его природа. Сидит свободно, карманы удобные. В целом довольна.',true,true,6,'ru',NULL,NULL,NOW() - INTERVAL '17 days', NOW() - INTERVAL '17 days'),
('rev-203','user-047','elevate-w-201',5,'Ношу как халат и на выход','Универсальное: дома удобно, с поясом и босоножками — уже образ. Очень довольна.',true,true,4,'ru',NULL,NULL,NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days'),
('rev-204','user-059','elevate-w-201',4,'Чуть великовато','Свободный крой — взяла бы на размер меньше. Качество льна отличное, не пожалела.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days'),
('rev-205','user-071','elevate-w-201',5,'Лучшее на лето','Носила в отпуске почти каждый день, стирается легко. Рекомендую всем любительницам льна.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
-- w-202 Velvet Night (4)
('rev-206','user-001','elevate-w-202',5,'Платье-вамп','Бархат глубокого бордового, открытая спина смотрится роскошно. На юбилей — идеально.',true,true,15,'ru',NULL,NULL,NOW() - INTERVAL '30 days', NOW() - INTERVAL '30 days'),
('rev-207','user-043','elevate-w-202',5,'Дорого выглядит','За свою цену смотрится как люкс. Бархат не вытирается, сидит по фигуре. В восторге.',true,true,9,'ru',NULL,NULL,NOW() - INTERVAL '24 days', NOW() - INTERVAL '24 days'),
('rev-208','user-015','elevate-w-202',4,'Красивое, но в пол','Мне 162 — длинновато, отдала подшить. После этого идеально. Цвет шикарный.',true,true,5,'ru',NULL,NULL,NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days'),
('rev-209','user-065','elevate-w-202',5,'Комплименты весь вечер','Открытая спина — изюминка. Бархат приятный, не электризуется. Однозначно рекомендую.',false,true,3,'ru',NULL,NULL,NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days'),
-- w-203 Bardot (3)
('rev-210','user-005','elevate-w-203',5,'Универсальный топ','Открытые плечи — женственно, резинка держит, не сползает. Беру в нескольких цветах.',true,true,7,'ru',NULL,NULL,NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days'),
('rev-211','user-049','elevate-w-203',4,'Хороший, тонковат','Топ приятный, но ткань тонкая — заметно бельё. В остальном за свою цену отлично.',true,true,4,'ru',NULL,NULL,NOW() - INTERVAL '11 days', NOW() - INTERVAL '11 days'),
('rev-212','user-073','elevate-w-203',5,'На лето то что надо','Лёгкий, не жарко, хорошо смотрится с джинсами и юбкой. Довольна покупкой.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days'),
-- w-204 Satin Slip Skirt (4)
('rev-213','user-019','elevate-w-204',5,'Юбка-хамелеон','Цвет шампань переливается, с разными верхами смотрится по-разному. Очень нравится.',true,true,8,'ru',NULL,NULL,NOW() - INTERVAL '26 days', NOW() - INTERVAL '26 days'),
('rev-214','user-045','elevate-w-204',4,'Красивая, но маркая','Атлас красивый, но на светлом видны зацепки. Аккуратно носить. Длина и крой отличные.',true,true,5,'ru',NULL,NULL,NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days'),
('rev-215','user-061','elevate-w-204',5,'Сидит идеально','По косой садится красиво, не топорщится. Разрез добавляет элегантности. Топ.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days'),
('rev-216','user-079','elevate-w-204',4,'Хорошая за свои деньги','Качество приятное, талия на резинке удобная. Сняла звезду за лёгкое просвечивание.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
-- w-205 Flare 70s (5)
('rev-217','user-011','elevate-w-205',5,'Ноги от ушей','Клёш визуально удлиняет ноги, высокая талия утягивает. Деним плотный. Влюбилась.',true,true,14,'ru',NULL,NULL,NOW() - INTERVAL '23 days', NOW() - INTERVAL '23 days'),
('rev-218','user-051','elevate-w-205',4,'Стильные, но длинные','На рост 165 пришлось подвернуть. Под каблук — идеально. Цвет и посадка супер.',true,true,6,'ru',NULL,NULL,NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days'),
('rev-219','user-025','elevate-w-205',5,'Привет из 70-х','Силуэт ретро, но смотрится современно. Сидят по фигуре, не растягиваются. Рекомендую.',true,true,4,'ru',NULL,NULL,NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days'),
('rev-220','user-067','elevate-w-205',3,'Узкие в бёдрах','Красивые, но в бёдрах села плотнее, чем ожидала. Берите с запасом на размер.',true,true,7,'ru',NULL,NULL,NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days'),
('rev-221','user-083','elevate-w-205',5,'Любимые джинсы','Ношу почти каждый день, форму держат. Клёш не выходит из моды. Очень довольна.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
-- w-206 Cape (3)
('rev-222','user-013','elevate-w-206',5,'Эффектная вещь','Кейп смотрится дорого и необычно. Тепло, шерсти достаточно. Получаю много вопросов где купила.',true,true,9,'ru',NULL,NULL,NOW() - INTERVAL '34 days', NOW() - INTERVAL '34 days'),
('rev-223','user-053','elevate-w-206',4,'Красиво, но непрактично','Руки в прорезях мёрзнут на сильном ветру. Зато выглядит потрясающе. На любителя.',true,true,6,'ru',NULL,NULL,NOW() - INTERVAL '25 days', NOW() - INTERVAL '25 days'),
('rev-224','user-077','elevate-w-206',5,'Ношу поверх всего','Удобно надевать на свитер или платье. Серый универсальный. Очень довольна.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days'),
-- w-207 Biker Lux (5)
('rev-225','user-001','elevate-w-207',5,'Косуха мечты','Эко-кожа мягкая, не пахнет химией, молнии плавные. Сидит идеально. Лучшая покупка сезона.',true,true,16,'ru',NULL,NULL,NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days'),
('rev-226','user-029','elevate-w-207',5,'Не отличить от кожи','Выглядит как настоящая кожа, при этом дешевле и не мнётся. Очень довольна качеством.',true,true,10,'ru',NULL,NULL,NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days'),
('rev-227','user-055','elevate-w-207',4,'Класс, но жестковата','Поначалу эко-кожа жёсткая, разнашивается. Фурнитура добротная. В целом отлично.',true,true,5,'ru',NULL,NULL,NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days'),
('rev-228','user-071','elevate-w-207',5,'Универсальная база','Идёт и к платьям, и к джинсам. Чёрный цвет насыщенный. Беру ещё в коричневом.',true,true,4,'ru',NULL,NULL,NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days'),
('rev-229','user-085','elevate-w-207',4,'Хорошая за свои деньги','Качество приятно удивило для эко-кожи. Чуть великовата в плечах, но это придирки.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days'),
-- w-208 Merino Roll (3)
('rev-230','user-021','elevate-w-208',5,'Не колется совсем','Меринос мягкий, под пальто идеально. Тонкая, но тёплая. Беру в нескольких цветах.',true,true,8,'ru',NULL,NULL,NOW() - INTERVAL '14 days', NOW() - INTERVAL '14 days'),
('rev-231','user-057','elevate-w-208',4,'Тёплая, аккуратная','Хорошо тянется, облегает не сильно. После стирки чуть села, стирайте бережно.',true,true,4,'ru',NULL,NULL,NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days'),
('rev-232','user-081','elevate-w-208',5,'Базовая вещь зимы','Молочный цвет идёт ко всему, ношу постоянно. Качество мериноса отличное.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days'),
-- w-209 Tailored Vest (3)
('rev-233','user-035','elevate-w-209',5,'Тренд сезона','Жилет смотрится стильно с брюками и джинсами. Подкладка приятная, сидит чётко.',true,true,7,'ru',NULL,NULL,NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days'),
('rev-234','user-063','elevate-w-209',4,'Хороший, но мнётся','Удлинённый крой нравится, но ткань заминается. В остальном за свои деньги отлично.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days'),
('rev-235','user-041','elevate-w-209',5,'Делает образ','Накинула поверх рубашки — сразу деловой вид. Бежевый универсальный. Рекомендую.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
-- w-210 Sheath (4)
('rev-236','user-007','elevate-w-210',5,'Идеально для офиса','Футляр сидит безупречно, ткань плотная, не просвечивает. Чувствую себя уверенно.',true,true,9,'ru',NULL,NULL,NOW() - INTERVAL '28 days', NOW() - INTERVAL '28 days'),
('rev-237','user-049','elevate-w-210',4,'Строго и аккуратно','Хорошее платье на работу, но в области бёдер плотновато. Берите по фигуре.',true,true,5,'ru',NULL,NULL,NOW() - INTERVAL '21 days', NOW() - INTERVAL '21 days'),
('rev-238','user-069','elevate-w-210',5,'Классика','Тёмно-синий универсальный, длина до колена приличная. Ношу с жакетом и без.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days'),
('rev-239','user-085','elevate-w-210',4,'Хорошее качество','Швы ровные, молния скрытая. Сняла звезду — хотелось бы чуть свободнее в груди.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
-- w-211 Chunky Turtleneck (4)
('rev-240','user-003','elevate-w-211',5,'Тёплый и яркий','Горчичный цвет поднимает настроение, вязка плотная, греет отлично. Очень уютный.',true,true,10,'ru',NULL,NULL,NOW() - INTERVAL '17 days', NOW() - INTERVAL '17 days'),
('rev-241','user-045','elevate-w-211',4,'Тепло, но объёмно','Реально крупная вязка — объёмный. Кому-то полнит. Мне нравится с узким низом.',true,true,6,'ru',NULL,NULL,NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days'),
('rev-242','user-067','elevate-w-211',5,'Спасает в мороз','Высокое горло защищает от ветра. Шерсть не колется. Беру на каждую зиму такие.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days'),
('rev-243','user-079','elevate-w-211',4,'Хороший свитер','Тёплый и мягкий, но немного появились катышки после стирки. В остальном доволна.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
-- w-212 Silk Cami (2)
('rev-244','user-015','elevate-w-212',5,'Настоящий шёлк','Приятно холодит, струится. Под жакет или с юбкой — всегда уместно. Дорогая база.',true,true,7,'ru',NULL,NULL,NOW() - INTERVAL '11 days', NOW() - INTERVAL '11 days'),
('rev-245','user-059','elevate-w-212',4,'Нежная, капризная','Шёлк требует деликатной стирки, но выглядит роскошно. Цвет пудровый очень красивый.',false,true,3,'ru',NULL,NULL,NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
-- w-213 Palazzo (3)
('rev-246','user-023','elevate-w-213',5,'Удобно и элегантно','Палаццо струятся, скрывают всё лишнее. Высокая талия удобная. Ношу на работу и вечером.',true,true,8,'ru',NULL,NULL,NOW() - INTERVAL '24 days', NOW() - INTERVAL '24 days'),
('rev-247','user-047','elevate-w-213',4,'Длинноваты','На невысокий рост длинноваты, нужен каблук или подшить. Сама ткань приятная.',true,true,4,'ru',NULL,NULL,NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days'),
('rev-248','user-073','elevate-w-213',5,'Летняя классика','Вискоза дышит, не жарко. Чёрный практичный. Сочетаю с топами и блузами.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
-- w-214 Jumpsuit (3)
('rev-249','user-005','elevate-w-214',5,'Образ за секунду','Надел — и готов стильный лук. Карманы функциональные, пояс подчёркивает талию.',true,true,9,'ru',NULL,NULL,NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days'),
('rev-250','user-055','elevate-w-214',4,'Стильно, но в туалет неудобно','Минус всех комбинезонов — раздеваться целиком. Зато выглядит отлично. Хаки классный.',true,true,6,'ru',NULL,NULL,NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
('rev-251','user-077','elevate-w-214',5,'Новинка понравилась','Села по фигуре, ткань плотная. Получила комплименты на работе. Рекомендую.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days'),
-- w-215 Long Line Knit (3)
('rev-252','user-031','elevate-w-215',5,'Уют в чистом виде','Длинный, мягкий, обнимает. Накидываю на всё. Серо-бежевый идёт ко всему.',true,true,7,'ru',NULL,NULL,NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days'),
('rev-253','user-061','elevate-w-215',4,'Хороший, но тянется','Удобный, но низ со временем немного вытянулся. За цену претензий нет.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days'),
('rev-254','user-083','elevate-w-215',5,'Накидка на каждый день','Тёплый и лёгкий, не сковывает. Ношу дома и на улицу. Очень довольна.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days'),
-- w-216 Boyfriend Blazer (4)
('rev-255','user-009','elevate-w-216',5,'Блейзер на все случаи','Свободный крой, рукава можно подвернуть. С джинсами и брюками одинаково хорош.',true,true,11,'ru',NULL,NULL,NOW() - INTERVAL '30 days', NOW() - INTERVAL '30 days'),
('rev-256','user-043','elevate-w-216',4,'Стильно, но широковат','Оверсайз действительно свободный. Если хотите по фигуре — берите меньше. Качество ок.',true,true,5,'ru',NULL,NULL,NOW() - INTERVAL '22 days', NOW() - INTERVAL '22 days'),
('rev-257','user-065','elevate-w-216',5,'Делает образ дороже','Накинула поверх футболки — уже смотрится собранно. Подкладка приятная. Рекомендую.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days'),
('rev-258','user-081','elevate-w-216',4,'Хороший серый','Цвет универсальный, ткань держит форму. Чуть длинные рукава, но подвернула.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
-- w-217 Denim A-line (2)
('rev-259','user-011','elevate-w-217',5,'Юбка из юности','А-силуэт скрывает бёдра, деним плотный. С футболкой и кедами — мой летний образ.',true,true,6,'ru',NULL,NULL,NOW() - INTERVAL '36 days', NOW() - INTERVAL '36 days'),
('rev-260','user-067','elevate-w-217',4,'Хорошая, но мини','Коротковата для меня, но это мой выбор размера. Деним и пошив отличные.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '14 days', NOW() - INTERVAL '14 days'),
-- w-218 Polka Tea Dress (4)
('rev-261','user-013','elevate-w-218',5,'Платье-настроение','Горошек и юбка-солнце — чувствую себя в кино. Лёгкое, женственное. Обожаю.',true,true,10,'ru',NULL,NULL,NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days'),
('rev-262','user-053','elevate-w-218',4,'Красивое, тонкое','Вискоза тонкая, нужна комбинация. Зато не жарко. Принт как на фото, не разочаровал.',true,true,5,'ru',NULL,NULL,NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days'),
('rev-263','user-069','elevate-w-218',5,'Романтичный образ','Рукава и вырез аккуратные, длина миди приличная. Ношу с босоножками. Очень нравится.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days'),
('rev-264','user-085','elevate-w-218',4,'Хорошее на лето','Лёгкое, дышит, садится хорошо. Сняла звезду — пуговицы хотелось бы покрепче.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days'),
-- w-219 Quilted Coat (3)
('rev-265','user-001','elevate-w-219',5,'Тёплое и лёгкое','Стёжка приятная, не продувает, пояс подчёркивает талию. Лёгкое для своей теплоты.',true,true,12,'ru',NULL,NULL,NOW() - INTERVAL '24 days', NOW() - INTERVAL '24 days'),
('rev-266','user-045','elevate-w-219',4,'Хорошее на 0/-5','Для лёгкого мороза идеально, в сильный холод прохладно. Стильно смотрится. Чёрный практичный.',true,true,5,'ru',NULL,NULL,NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days'),
('rev-267','user-071','elevate-w-219',5,'Ношу всю осень','Лёгкое, тёплое, длина закрывает бёдра. Беру ещё в оливковом. Очень довольна.',false,true,3,'ru',NULL,NULL,NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
-- w-220 Crop Hoodie (3)
('rev-268','user-029','elevate-w-220',5,'Уютное и милое','Лавандовый цвет нежный, начёс мягкий. С высокой талией смотрится отлично.',true,true,6,'ru',NULL,NULL,NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days'),
('rev-269','user-057','elevate-w-220',4,'Коротковато','Укороченное — на любителя, мне чуть коротко. Качество и цвет хорошие.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '11 days', NOW() - INTERVAL '11 days'),
('rev-270','user-079','elevate-w-220',5,'Для спорта и дома','Мягкое, не сковывает. Ношу на тренировки и на прогулку. Рекомендую.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days'),
-- w-221 Soft Jogger (3)
('rev-271','user-021','elevate-w-221',5,'Мягкие как пижама','Самые удобные джоггеры, не теряют форму после стирок. Ношу дома постоянно.',true,true,7,'ru',NULL,NULL,NOW() - INTERVAL '19 days', NOW() - INTERVAL '19 days'),
('rev-272','user-063','elevate-w-221',4,'Удобные, но маркие','Серый меланж собирает ворс и шерсть. Сами джоггеры отличные, удобный пояс.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days'),
('rev-273','user-081','elevate-w-221',5,'На каждый день','Не жаркие, не холодные, манжеты держат. За свою цену — супер.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
-- w-222 Flannel Check (3)
('rev-274','user-035','elevate-w-222',5,'Тёплая и уютная','Фланель мягкая, в клетку — классика. Ношу навыпуск с джинсами. Очень нравится.',true,true,6,'ru',NULL,NULL,NOW() - INTERVAL '28 days', NOW() - INTERVAL '28 days'),
('rev-275','user-047','elevate-w-222',4,'Хорошая, но большемерит','Свободный крой — взяла бы меньше. Качество фланели достойное, не линяет.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days'),
('rev-276','user-073','elevate-w-222',5,'Осенний фаворит','Красная клетка яркая, поднимает настроение. Тёплая, мягкая. Рекомендую.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
-- w-223 Satin Bomber (3)
('rev-277','user-009','elevate-w-223',5,'Нарядный casual','Атласный блеск и вышивка делают бомбер особенным. Изумрудный цвет роскошный.',true,true,8,'ru',NULL,NULL,NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days'),
('rev-278','user-051','elevate-w-223',4,'Красивый, тонкий','Для прохладной погоды тонковат, но как лёгкая куртка — отлично. Вышивка аккуратная.',true,true,4,'ru',NULL,NULL,NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days'),
('rev-279','user-085','elevate-w-223',5,'Изюминка гардероба','Сразу выделяет образ. Села хорошо, рёбра на манжетах плотные. Очень довольна.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days'),
-- w-224 Pleated Maxi (3)
('rev-280','user-019','elevate-w-224',5,'Развевается красиво','Плиссе держит складку, на ходу красиво струится. Пыльно-розовый нежный.',true,true,7,'ru',NULL,NULL,NOW() - INTERVAL '22 days', NOW() - INTERVAL '22 days'),
('rev-281','user-059','elevate-w-224',4,'Длинная, под каблук','В пол — нужен каблук или подшить. Цвет и плиссировка отличные. Лёгкая.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '14 days', NOW() - INTERVAL '14 days'),
('rev-282','user-077','elevate-w-224',5,'Очень женственно','С топом и босоножками — летний образ мечты. Складка не расходится. Рекомендую.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
-- w-225 Linen Blazer (3)
('rev-283','user-007','elevate-w-225',5,'Жакет для жары','Лён дышит, в жару в пиджаке не плавлюсь. Смотрится аккуратно. Идеален для лета.',true,true,6,'ru',NULL,NULL,NOW() - INTERVAL '40 days', NOW() - INTERVAL '40 days'),
('rev-284','user-049','elevate-w-225',4,'Мнётся, но красиво','Лён есть лён — складки. Но выглядит дорого и непринуждённо. Бежевый универсальный.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days'),
('rev-285','user-069','elevate-w-225',5,'Лёгкий и стильный','Без подкладки — не жарко. Ношу с брюками и джинсами. Очень довольна.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days'),
-- w-226 Ribbed Bodycon (3)
('rev-286','user-005','elevate-w-226',5,'Подчёркивает фигуру','Рубчик тянется и садится по телу красиво. Чёрный универсальный. Ношу с кроссовками и каблуком.',true,true,8,'ru',NULL,NULL,NOW() - INTERVAL '11 days', NOW() - INTERVAL '11 days'),
('rev-287','user-061','elevate-w-226',4,'Облегает плотно','Платье красивое, но требует уверенности — облегает всё. Качество трикотажа хорошее.',true,true,4,'ru',NULL,NULL,NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days'),
('rev-288','user-083','elevate-w-226',5,'База на выход','С жакетом днём, с украшениями вечером. Не просвечивает, держит форму. Рекомендую.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
-- m-201 Linen Resort (4)
('rev-289','user-004','elevate-m-201',5,'Спасение в жару','Лён дышит, в +35 комфортно. Свободный крой, открытый воротник. Беру в отпуск.',true,true,11,'ru',NULL,NULL,NOW() - INTERVAL '21 days', NOW() - INTERVAL '21 days'),
('rev-290','user-046','elevate-m-201',4,'Хорошая, мнётся','Как любой лён — мятая к вечеру. Но это нормально для материала. Качество достойное.',true,true,5,'ru',NULL,NULL,NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days'),
('rev-291','user-062','elevate-m-201',5,'Отпускной мастхэв','Лёгкая, быстро сохнет, белый цвет освежает загар. Очень доволен.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '11 days', NOW() - INTERVAL '11 days'),
('rev-292','user-080','elevate-m-201',4,'Большемерит','Свободный крой плюс размер — взял бы меньше. Лён приятный. В целом доволен.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days'),
-- m-202 Trucker Denim (4)
('rev-293','user-008','elevate-m-202',5,'Куртка на все времена','Деним плотный, классический trucker. Подходит ко всему. Сел идеально, рекомендую.',true,true,13,'ru',NULL,NULL,NOW() - INTERVAL '30 days', NOW() - INTERVAL '30 days'),
('rev-294','user-044','elevate-m-202',4,'Жёсткая поначалу','Деним сначала жёсткий, потом разнашивается. Качество пошива отличное, швы крепкие.',true,true,6,'ru',NULL,NULL,NOW() - INTERVAL '22 days', NOW() - INTERVAL '22 days'),
('rev-295','user-066','elevate-m-202',5,'Беру второй раз','Первая прослужила пару лет. Качество стабильное. Синий цвет классический.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days'),
('rev-296','user-084','elevate-m-202',4,'Хорошая джинсовка','За свои деньги отлично. Пуговицы крепкие, карманы удобные. Чуть коротковата в рукавах.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
-- m-203 Lambswool Crew (4)
('rev-297','user-012','elevate-m-203',5,'Мягкий и тёплый','Шерсть совсем не колется, греет отлично. Тёмно-синий универсальный. Под рубашку — супер.',true,true,9,'ru',NULL,NULL,NOW() - INTERVAL '25 days', NOW() - INTERVAL '25 days'),
('rev-298','user-048','elevate-m-203',4,'Хороший, но катышки','Появились небольшие катышки на боках. Сам свитер приятный и тёплый. Стирать бережно.',true,true,5,'ru',NULL,NULL,NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days'),
('rev-299','user-070','elevate-m-203',5,'Качество шерсти','Чувствуется хороший ламбсвул, не как акрил. Держит тепло, не растягивается.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '11 days', NOW() - INTERVAL '11 days'),
('rev-300','user-082','elevate-m-203',4,'Тёплый базовый','Хороший свитер на каждый день, размер в размер. Доволен покупкой.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days'),
-- m-204 Tactical Cargo (3)
('rev-301','user-006','elevate-m-204',5,'Карманы для всего','Карго-карманы вместительные, ткань плотная. Прямой крой, не мешковатые. Удобные.',true,true,7,'ru',NULL,NULL,NOW() - INTERVAL '24 days', NOW() - INTERVAL '24 days'),
('rev-302','user-052','elevate-m-204',4,'Хорошие, плотные','Качественный хлопок, но жестковаты вначале. После стирки мягче. Хаки практичный.',true,true,4,'ru',NULL,NULL,NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days'),
('rev-303','user-074','elevate-m-204',5,'Рабочая лошадка','Ношу на дачу и в город, не боятся грязи. Карманы реально функциональные.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
-- m-205 Down Vest (3)
('rev-304','user-010','elevate-m-205',5,'Тепло без рукавов','Жилет греет корпус, руки свободны. Поверх свитера — идеально для осени.',true,true,6,'ru',NULL,NULL,NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days'),
('rev-305','user-056','elevate-m-205',4,'Лёгкий, но тонкий','Для +5/+10 хорошо, в холоднее нужен слой потеплее. Пух не вылезает. Доволен.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days'),
('rev-306','user-076','elevate-m-205',5,'Удобно в межсезонье','Не сковывает руки, тепло. Стойка защищает шею. Беру на каждую осень.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
-- m-206 LS Polo (3)
('rev-307','user-014','elevate-m-206',5,'Поло на прохладу','Длинный рукав и пике — отличное сочетание. Бордовый благородный. Ношу под пиджак.',true,true,5,'ru',NULL,NULL,NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days'),
('rev-308','user-058','elevate-m-206',4,'Хорошее, село','После стирки чуть село, стирайте на 30. Качество пике достойное.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days'),
('rev-309','user-078','elevate-m-206',5,'Замена футболке','Аккуратнее чем футболка, удобнее чем рубашка. Воротник держит форму. Доволен.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days'),
-- m-207 Unstructured Blazer (4)
('rev-310','user-002','elevate-m-207',5,'Пиджак-кэжуал','Мягкий, без жёсткой подкладки, носится с футболкой. Очень удобный, не сковывает.',true,true,8,'ru',NULL,NULL,NOW() - INTERVAL '32 days', NOW() - INTERVAL '32 days'),
('rev-311','user-050','elevate-m-207',4,'Стильный, но мнётся','Неструктурированный — отсюда и заломы. Зато расслабленный вид. Серый универсальный.',true,true,5,'ru',NULL,NULL,NOW() - INTERVAL '22 days', NOW() - INTERVAL '22 days'),
('rev-312','user-072','elevate-m-207',5,'Универсальная вещь','И на встречу, и на свидание. Сидит хорошо, рукава в меру. Рекомендую.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days'),
('rev-313','user-084','elevate-m-207',4,'Хороший за свои деньги','Качество достойное, подойдёт под casual. Чуть свободноват в плечах для меня.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
-- m-208 Zip Hoodie (4)
('rev-314','user-016','elevate-m-208',5,'Тёплое и удобное','Молния плавная, начёс мягкий, капюшон держит форму. Ношу не снимая. Отличное худи.',true,true,9,'ru',NULL,NULL,NOW() - INTERVAL '17 days', NOW() - INTERVAL '17 days'),
('rev-315','user-054','elevate-m-208',4,'Хорошее, тонковато','Для весны-осени идеально, зимой нужен слой. Качество пошива на уровне.',true,true,4,'ru',NULL,NULL,NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days'),
('rev-316','user-068','elevate-m-208',5,'На каждый день','Удобное, карманы глубокие, не растянулось. Серый меланж практичный. Доволен.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days'),
('rev-317','user-082','elevate-m-208',4,'Норм за свои деньги','Обычное добротное худи, ничего лишнего. Сел в размер. Рекомендую как базу.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
-- m-209 Henley Tee (3)
('rev-318','user-020','elevate-m-209',5,'Интереснее обычной футболки','Планка с пуговицами добавляет стиля. Хлопок мягкий, тянется. Беру несколько.',true,true,6,'ru',NULL,NULL,NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days'),
('rev-319','user-064','elevate-m-209',4,'Хорошая, села','После стирки немного села, в остальном отлично. Серый универсальный.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days'),
('rev-320','user-080','elevate-m-209',5,'База с характером','Не такая скучная как обычный тишёрт. Сидит хорошо, не просвечивает. Доволен.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days'),
-- m-210 Tapered Comfort (3)
('rev-321','user-012','elevate-m-210',5,'Удобные джинсы','Стрейч делает их комфортными на весь день, при этом выглядят аккуратно. Сидят отлично.',true,true,7,'ru',NULL,NULL,NOW() - INTERVAL '23 days', NOW() - INTERVAL '23 days'),
('rev-322','user-046','elevate-m-210',4,'Хорошие, чуть зауженные','Книзу узковаты для меня, но это особенность модели. Качество денима достойное.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days'),
('rev-323','user-070','elevate-m-210',5,'Замена классике','Серо-синий универсальный, садятся по фигуре. Удобнее обычных джинсов. Рекомендую.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
-- m-211 Expedition Parka (5)
('rev-324','user-004','elevate-m-211',5,'Пережил -35','Реально экспедиционная парка, не замёрз в лютый мороз. Капюшон с опушкой, карманы тёплые.',true,true,17,'ru',NULL,NULL,NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days'),
('rev-325','user-038','elevate-m-211',5,'Лучшая зимняя куртка','Тёплая, ветрозащитная, при этом не как скафандр. Стоит своих денег на 100%.',true,true,10,'ru',NULL,NULL,NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days'),
('rev-326','user-056','elevate-m-211',4,'Тёплая, но тяжеловата','Греет отлично, но ощутимо тяжёлая по сравнению с пуховиком. Для морозов — то что надо.',true,true,5,'ru',NULL,NULL,NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days'),
('rev-327','user-074','elevate-m-211',5,'Спокойно за зиму','Купил перед сильными холодами — не пожалел. Капюшон регулируется, манжеты плотные.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days'),
('rev-328','user-082','elevate-m-211',4,'Большемерит','Взял свой размер — великовата, но для парки нормально, поддеваю свитер. Тёплая.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
-- m-212 Graphic Crew (3)
('rev-329','user-026','elevate-m-212',5,'Принт не облез','После многих стирок принт как новый. Футер плотный, не просвечивает. Доволен.',true,true,5,'ru',NULL,NULL,NOW() - INTERVAL '19 days', NOW() - INTERVAL '19 days'),
('rev-330','user-060','elevate-m-212',4,'Хороший свитшот','Принт минималистичный, не кричащий. Сел в размер. За цену претензий нет.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days'),
('rev-331','user-078','elevate-m-212',5,'Удобный и стильный','Носится с джинсами и джоггерами. Чёрный практичный, начёс мягкий. Рекомендую.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
-- m-213 Flannel Overshirt (3)
('rev-332','user-006','elevate-m-213',5,'Рубашка-куртка','Плотная фланель, ношу поверх футболки вместо лёгкой куртки. Клетка стильная.',true,true,6,'ru',NULL,NULL,NOW() - INTERVAL '28 days', NOW() - INTERVAL '28 days'),
('rev-333','user-048','elevate-m-213',4,'Тёплая, плотная','Хороший овершот, но в плечах чуть широковат. Качество фланели отличное.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days'),
('rev-334','user-076','elevate-m-213',5,'Осенний фаворит','Сине-зелёная клетка сдержанная, идёт ко всему. Тепло и удобно. Доволен.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
-- m-214 Swim Shorts (2)
('rev-335','user-020','elevate-m-214',5,'Быстро сохнут','Из воды вышел — через 15 минут сухие. Пояс удобный, подкладка не натирает. Доволен.',true,true,5,'ru',NULL,NULL,NOW() - INTERVAL '40 days', NOW() - INTERVAL '40 days'),
('rev-336','user-064','elevate-m-214',4,'Хорошие шорты','За свою цену отлично. Тёмно-синий не маркий. Сетчатая подкладка немного грубовата.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '14 days', NOW() - INTERVAL '14 days'),
-- m-215 Zip Cardigan (3)
('rev-337','user-012','elevate-m-215',5,'Удобнее свитера','Молния спасает — не надо тянуть через голову. Тёплый, стойка защищает шею.',true,true,5,'ru',NULL,NULL,NOW() - INTERVAL '22 days', NOW() - INTERVAL '22 days'),
('rev-338','user-058','elevate-m-215',4,'Хороший кардиган','Тёмно-серый практичный, вязка плотная. Молния иногда подклинивает, но мелочь.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '14 days', NOW() - INTERVAL '14 days'),
('rev-339','user-072','elevate-m-215',5,'На каждый день','Ношу в офис и на прогулку. Удобно расстегнуть когда жарко. Доволен.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
-- m-216 Tech Pants (3)
('rev-340','user-022','elevate-m-216',5,'Брюки-трансформеры','И на работу, и на пробежку. Тянутся, не мнутся, вода скатывается. Технологично.',true,true,7,'ru',NULL,NULL,NOW() - INTERVAL '11 days', NOW() - INTERVAL '11 days'),
('rev-341','user-054','elevate-m-216',4,'Удобные, но синтетика','Комфортные и практичные, но в жару кожа не дышит. Для активностей — отлично.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days'),
('rev-342','user-084','elevate-m-216',5,'Новинка зашла','Лёгкие, тянутся во все стороны, держат форму. Чёрный универсальный. Рекомендую.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
-- m-217 Mac Coat (3)
('rev-343','user-002','elevate-m-217',5,'Строгий и лёгкий','Тренч прямого кроя, потайная застёжка смотрится чисто. От ветра защищает. Бежевый классика.',true,true,8,'ru',NULL,NULL,NOW() - INTERVAL '36 days', NOW() - INTERVAL '36 days'),
('rev-344','user-050','elevate-m-217',4,'Хороший, рукава длинные','Тренч отличный, но рукава длинноваты, подшил. Ткань водоотталкивающая, проверил под дождём.',true,true,4,'ru',NULL,NULL,NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days'),
('rev-345','user-066','elevate-m-217',5,'Образ джентльмена','С костюмом и с джинсами одинаково хорош. Длина удачная. Очень доволен.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days'),
-- m-218 Long Sleeve Tee (2)
('rev-346','user-016','elevate-m-218',5,'Идеальный базовый лонгслив','Плотный, не просвечивает, не растянулся. Беру по несколько штук разных цветов.',true,true,6,'ru',NULL,NULL,NOW() - INTERVAL '17 days', NOW() - INTERVAL '17 days'),
('rev-347','user-068','elevate-m-218',4,'Хороший, чуть короткий','Качество отличное за цену, но в длину чуть коротковат. Заправляю — норм.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days'),
-- m-219 Half-Zip Knit (3)
('rev-348','user-026','elevate-m-219',5,'Стильный джемпер','Половинная молния выглядит аккуратно. Овсяный цвет приятный, тёплый. Под куртку идеально.',true,true,5,'ru',NULL,NULL,NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days'),
('rev-349','user-060','elevate-m-219',4,'Хороший, но тонкий','Для осени отлично, зимой нужен слой. Вязка аккуратная, молния качественная.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days'),
('rev-350','user-078','elevate-m-219',5,'Универсальный','С рубашкой и с футболкой, в офис и на прогулку. Доволен качеством за эту цену.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
-- m-220 Wool Overshirt (3)
('rev-351','user-006','elevate-m-220',5,'Тёплая куртка-рубашка','Шерстяное сукно плотное, греет как лёгкая куртка. Серый универсальный. Стильно.',true,true,7,'ru',NULL,NULL,NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days'),
('rev-352','user-052','elevate-m-220',4,'Хорошая, колется через футболку','Поверх тонкой футболки шерсть немного ощущается. С лонгсливом — отлично. Тёплая.',true,true,3,'ru',NULL,NULL,NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days'),
('rev-353','user-082','elevate-m-220',5,'Новинка понравилась','Промежуточный слой между рубашкой и курткой. Удобно в межсезонье. Рекомендую.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
-- m-221 Tipped Polo (2)
('rev-354','user-008','elevate-m-221',5,'Аккуратная классика','Контрастная окантовка делает поло интереснее. Пике плотное, воротник держит форму.',true,true,5,'ru',NULL,NULL,NOW() - INTERVAL '38 days', NOW() - INTERVAL '38 days'),
('rev-355','user-064','elevate-m-221',4,'Хорошее поло','За свои деньги отлично, но белое слегка просвечивает. Сидит хорошо.',false,true,2,'ru',NULL,NULL,NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days'),
-- m-222 Coach Jacket (1)
('rev-356','user-022','elevate-m-222',5,'Лёгкая и удобная','Минималистичная куртка на кнопках, от ветра защищает. Подкладка приятная. Ношу постоянно.',true,true,4,'ru',NULL,NULL,NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days')
ON CONFLICT (user_id, product_id) DO NOTHING;

-- ============================================================================
-- 6. ПЕРЕСЧЁТ АГРЕГАТОВ РЕЙТИНГА для всех затронутых товаров (обе пары колонок)
-- ============================================================================
UPDATE products p SET
  average_rating = sub.avg_rating,
  review_count   = sub.cnt,
  rating_avg     = sub.avg_rating,
  rating_count   = sub.cnt,
  updated_at     = NOW()
FROM (
  SELECT product_id, ROUND(AVG(rating)::numeric, 2) AS avg_rating, COUNT(*) AS cnt
  FROM reviews
  WHERE is_approved = TRUE
  GROUP BY product_id
) sub
WHERE p.id = sub.product_id;

COMMIT;

-- ============================================================================
-- ПРОВЕРКА
-- ============================================================================
SELECT COUNT(*) AS products_batch2 FROM products WHERE id LIKE 'elevate-w-2%' OR id LIKE 'elevate-m-2%';
SELECT COUNT(*) AS users_batch2     FROM users    WHERE id LIKE 'user-0%' AND id >= 'user-041';
SELECT COUNT(*) AS reviews_batch2   FROM reviews  WHERE id LIKE 'rev-2%' OR id LIKE 'rev-3%';
SELECT COUNT(*) AS reviews_total    FROM reviews;
SELECT COUNT(*) AS products_total   FROM products;
